[project]
authors = ["Luis Pedro Coelho <luis@luispedro.org>"]
channels = ["conda-forge", "bioconda"]
name = "db_harmonisation"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
rgi = { version = ">=6.0.3,<7", channel = "bioconda" }
jug = ">=2.3.1,<3"

[pypi-dependencies]
argnorm = { path = ".." }
