name: Test argNorm

on:
  - push
  - pull_request

jobs:
  build:
    runs-on: ubuntu-22.04
    strategy:
      fail-fast: false
      matrix:
        python-version:
          - "3.7"
          - "3.8"
          - "3.9"
          - "3.10"
          - "3.11"
          - "3.12"
          # - "3.13"

    steps:
    - uses: actions/checkout@v4
    - name: Install uv
      uses: astral-sh/setup-uv@v5
      with:
        python-version: ${{ matrix.python-version }}
        version: "0.5.29"
        enable-cache: true
        cache-dependency-glob: "uv.lock"
    - name: Install dependencies
      run: |
        uv sync --all-extras --dev
        uv pip install flake8 pytest
    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 argnorm --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 argnorm --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    - name: Test with pytest
      run: |
        uv run pytest tests/
    - name: Test with argNorm command
      run: |
        for t in integration_tests/*.py; do
          echo "Running $t ..."
          python $t
        done
